I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/prologue.rpy", line 159, in script
    "Орден? Измена? Переворот? Как такое может быть? Ты знаком с
Exception: Sayer '"Орден? Измена? Переворот? Как такое может быть? Ты знаком с
    летописями Крестовых походов и в чём никогда не мог усомниться,
    так это в лояльности Ордена к Церкви и Монарху. В конце концов,
    именно Орден всегда был в авангарде армии. Именно Орден нёс
    самые большие потери в походах на эльфов. Вот уж действительно
    экстраординарное утро. Может твой друг перебрал с вином? При
    дворе ходят слухи про его злоупотребление альгулем…К сожалению,
    ты лишь недавно вернулся с поимки "' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/prologue.rpy", line 159, in script
    "Орден? Измена? Переворот? Как такое может быть? Ты знаком с
  File "D:\progs\RenPy\renpy-8.2.0-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "D:\progs\RenPy\renpy-8.2.0-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\progs\RenPy\renpy-8.2.0-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer '"Орден? Измена? Переворот? Как такое может быть? Ты знаком с
    летописями Крестовых походов и в чём никогда не мог усомниться,
    так это в лояльности Ордена к Церкви и Монарху. В конце концов,
    именно Орден всегда был в авангарде армии. Именно Орден нёс
    самые большие потери в походах на эльфов. Вот уж действительно
    экстраординарное утро. Может твой друг перебрал с вином? При
    дворе ходят слухи про его злоупотребление альгулем…К сожалению,
    ты лишь недавно вернулся с поимки "' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
honestProject 1.0
Tue Mar  5 00:53:54 2024
